# Ensure cluster exists before doing anything
local('k3d cluster list | grep -q nebula || ctlptl apply -f ctlptl.yaml')

allow_k8s_contexts('k3d-nebula')

# Load generated Tiltfile (from `just synth`)
load_dynamic('./dist/Tiltfile.generated')
